greenIT/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls'))

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.schedule, name='schedule'),
    path('about/', views.about, name='about'),
    path('teacher/', views.teacher, name='teacher'),
    path('modules', views.modules, name='modules'),
    path('modules/<slug:module_slug>', views.module_view, name='module'),
    path('topics/<slug:topic_slug>', views.topic_view, name='topic'),

]

users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register_user, name='register'),
    path('log_out/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='profile'),

]

main/models.py
from django.db import models


# Create your models here.
class Module(models.Model):
    title = models.CharField(max_length=300, verbose_name='Модуль')
    enabled = models.BooleanField(verbose_name='Доступен')
    description = models.TextField(verbose_name='Описание', null=True)
    module_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/modules/{self.module_slug}'

    class Meta:
        verbose_name = 'Модуль'
        verbose_name_plural = 'Модули'
        ordering = ['title', 'id']


class Topic(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name='Модуль')
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    home_tasks = models.TextField(verbose_name='Домашние задачи', null=True, blank=True)
    link = models.CharField(max_length=500, verbose_name='Ссылка на google-форму для ответов', null=True, blank=True)
    video = models.CharField(max_length=300, null=True, blank=True, verbose_name='Запись занятия')
    topic_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'topics/{self.topic_slug}/'

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'
        ordering = ['title', 'id']


class Subtopic(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='Тема')
    title = models.CharField(max_length=300, verbose_name='Название')
    content = models.TextField(verbose_name='Содержание', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подтема'
        verbose_name_plural = 'Поддемы'
        ordering = ['topic', 'id']

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {'username': 'Имя пользователя',
                  'first_name': 'Имя',
                  'last_name': 'Фамилия',
                  'email': 'Электронная почта',
                  'password1': 'Пароль',
                  'password2': 'Подтверждение пароля'}

main/views.py
from django.shortcuts import render
from . models import *
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'main/index.html')


@login_required(login_url='users:login')
def schedule(request):
    return render(request, 'main/schedule.html')


def about(request):
    return render(request, 'main/about.html')


def teacher(request):
    return render(request, 'main/teacher.html')


@login_required(login_url='users:login')
def modules(request):
    all_modules = Module.objects.order_by('title')

    context = {'modules': all_modules}

    return render(request, 'main/modules.html', context)


@login_required(login_url='users:login')
def module_view(request, module_slug):
    current_module = Module.objects.get(module_slug=module_slug)
    topics = Topic.objects.prefetch_related('module').filter(module=current_module)
    context = {'module': current_module, 'topics': topics}

    return render(request, 'main/module.html', context)


@login_required(login_url='users:login')
def topic_view(request, topic_slug):
    current_topic = Topic.objects.get(topic_slug=topic_slug)
    subtopics = Subtopic.objects.prefetch_related('topic').filter(topic=current_topic)

    context = {'topic': current_topic, 'subtopics': subtopics}

    return render(request, 'main/topic.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import UserRegisterForm


# Create your views here.
def register_user(request):
    if request.method != 'POST':
        form = UserRegisterForm()
    else:
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')


def user_profile(request):
    user = request.user
    context = {'user': user}
    return render(request, 'registration/profile.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}О курсе{% endblock %}

{% block page_header %}
    <h1>О курсе</h1>
{% endblock %}


{% block content %}
    <div class="about">
        <h3>Мы представляем вашему вниманию курс по программированию "Практический Python"</h3>
        <ul>
            <li>Наш курс позволит вам изучить основы популярного и востребованного языка программирования.</li>
            <li>Вы научитесь использовать Python для решения самых разных практических задач.</li>
            <li>По итогу прохождения курса вы
                пополните свое портфолио тремя практическими проектами и получите сертификат о прохождении курса.</li>
        </ul>
    </div>

    <div class="for_users">
        <h3>Кому подойдет данный курс?</h3>
        <p>Данный курс рассчитан на потенциальных обучающихся в возрасте от 14 до 18 лет. Курс подойдет, как для новичков,
        так и для тех, у кого уже имеется опыт в программировании и они желают повысить свой уровень, поучаствовать в
        разработке серьезных практических проектов. В рамках курса, благодаря общению между собой, обучающиеся также смогут
        повысить уровень "мягких навыков" - soft skills, получить опыт работы в команде, приобрести ценные знания.</p>
    </div>

    <div class="course_content">
        <h3>Структура курса</h3>
        <p>Наш курс имеет модульную структуру и разделен на 4 практических модуля, которые будут открываться по
        ходу прохождения курса.<br><br>В каждом модуле вы будете шаг за шагом проходить выстроенные в логической
        последовательности темы, взаимосвязанные между собой. По итогу прохождения каждой темы вам
        будет предложено выполнить домашнее задание, состоящее из ряда практических задач.<br><br>Каждому участнику
        на протяжении прохождения курса будет дана обратная связь по решению домашних задач и возникающим вопросам,
        которые можно задавать в группах в
        <a href="https://t.me/+HXHMJPBWdUcyZDFi" target="_blank">Telegram</a> или
        <a href="https://vk.me/join/71b1yYYGbyuuOQGdBw8ec6YXaqESLqyHevI=" target="_blank">VK</a>. Также в
        течение прохождения каждого модуля будут организованы несколько онлайн встреч на платформе
        <a href="https://discord.gg/EUTJSmF4" target="_blank">Discord</a>, даты которых вы сможете найти в разделе
        <a href="{% url 'main:schedule' %}">Расписание</a>.<br><br>Теорию и разбор задач по каждой теме вы сможете найти в
        текстовом виде на нашем сайте, а также в формате видео на
            <a href="https://youtube.com/playlist?list=PLn6kz1xByugtaOa2CeA2IQldXmlpWOROj&si=eRz9tUxn9I8GxF3I"
               target="_blank">Youtube</a></p>
    </div>

    <div class="modules">
        <h3>Модули</h3>
        <ul>
            <li>
                <h5>Модуль 1. Основы Python.</h5>
                <p>В рамках данного модуля обучающимся предстоит ознакомиться с основными понятиями в Python. Познакомиться
                с системой контроля версий. Научиться решать несложные практические задачи с применением языка Python.
                Ознакомиться с основными парадигмами программирования. Полученные в данном модуле знания пригодятся в
                дальнейшем при разработке более серьезных проектов. Отнеситесь к прохождению данного модуля ответственно.</p>
            </li>
            <li>
                <h5>Модуль 2. Основы Django</h5>
                <p>В рамках второго модуля участникам предлагается изучить основы популярного веб-фреймворка Django и
                разработать полноценное приложение. В ходе прохождения модуля участники познакомятся с основами проектирования
                и администрирования баз данных, узнают, что такое RestAPI, HHTP-запросы, разработают полноценный сайт.</p>
            </li>
            <li>
                <h5>Модуль 3. Разработка чат-ботов</h5>
                <p>Третий модуль знакомит участников с популярной библиотекой в Python: PyTelegramBotApi и ее возможностями
                В рамках данного модуля обучающимся предлагается разработать несложного чат-бота на платформе Telegram со
                множеством возможностей, который может стать настоящим помощником в решении повседневных практических задач.
                Знания, полученные в данном модуле могут быть использованы в дальнейшем при разработке собственного проекта.</p>
            </li>
            <li>
                <h5>Модуль 4. Разработка 2D-игр</h5>
                <p>Думаем, что каждый из вас когда-либо играл или хотя бы слышал о 2D-играх, таких, как Змейка, тетрис,
                Аркаоид, Инопланетное вторжение и многих других. В рамках данного модуля участникам курса предлагается
                разработать свою полноценную 2D-игру с использованием возможностей Python, а именно библиотеки для
                разработки игр - pygame. Данный модуль не только обучает разработке игр, но и дает практические знания в
                области разработки десктоп-интерфейсов и обработки графики.</p>
            </li>
        </ul>
    </div>

    <link rel="stylesheet" href="{% static 'main/css/about.css' %}">
{% endblock %}

main/templates/main/base.html
{% load django_bootstrap5 %}
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <link rel="icon" href="{% static 'main/images/icon/icon.jpeg' %}">

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'main:index' %}" style="font-size: 24pt" onmouseover="this.style.color='#90EE90'"
                onmouseout="this.style.color='gold'">
                    <img src="{% static 'main/images/logo/logo.jpeg' %}" alt="logo"
                    class="nav-logo" width="60px" height=60px" style="border-radius: 50%">
                     GreenIT</a>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="font-size: 14pt">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Обучающимся
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a href="{% url 'main:about' %}" class="dropdown-item">О курсе</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:teacher' %}">Преподаватель</a></li>
                        </ul>
                    </li>
                </ul>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="font-size: 14pt">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:schedule' %}">Расписание</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:modules' %}">Модули</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto" style="font-size: 14pt">
                        {% if user.is_authenticated %}
                            <span class="navbar-text" style="color: mediumspringgreen;"><strong>Здравствуйте, {{ user.username }}!</strong></span>
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Управление</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:profile' %}">Перейти в профиль</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                                </li>
                            {% endif %}

                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'users:register' %}" class="nav-link">Регистрация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="base">
                <div class="header pb-2 mb-2 border-bottom">
                    {% block page_header %}{% endblock %}
                </div>
                <div class="content">
                    {% block content %}{% endblock %}
                </div>

                <div class="footer">
                    <div style="float: left; margin-right: 15px">
                        <h6>По возникающим вопросам писать на почту
                            <br>или в телеграм</h6>
                        <div>greensails72@gmail.com</div>
                        <div><a href="https://t.me/Vanyok77797" style="color: white">Иван Алексеев</a></div>
                    </div>

                    <div style="float: left; margin-right: 15px">
                        <h6 style="text-align: left;  width: 135px">Чаты в соцсетях</h6>
                        <div style=" float: left; margin-right: 15px">
                            <a href="https://vk.me/join/71b1yYYGbyuuOQGdBw8ec6YXaqESLqyHevI=" target="_blank"><img src="{% static 'main/images/logo/img_1.png' %}" alt="" width="60px" height="60px"></a>
                        </div>

                        <div style="margin-top: 5px;">
                            <a href="https://t.me/+HXHMJPBWdUcyZDFi" target="_blank"><img src="{% static 'main/images/logo/img_2.png' %}" alt="" width="60px" height="60px"></a>
                        </div>
                    </div>
                    <div style="float: left">
                        <h6>Сервер в Discord</h6>
                        <div style="margin-right: 15px; float: left">
                            <a href="https://discord.gg/EUTJSmF4" target="_blank"><img src="{% static 'main/images/logo/ds_logo.png' %}" alt="Discord" width="60px" height="60px"></a>
                        </div>
                    </div>
                </div>
            </div>
        </main>



        <div class="btn-up btn-up_hide"></div>
        <script src="{% static 'main/js/base.js' %}"></script>
    </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Главная{% endblock %}

{% block page_header %}
    <h1>Главная</h1>
{% endblock %}

{% block content %}
    <div class="about">
        <h3>Мы представляем вашему вниманию курс по программированию "Практический Python"</h3>
        <ul>
            <li>Наш курс позволит вам изучить основы популярного и востребованного языка программирования.</li>
            <li>Вы научитесь использовать Python для решения самых разных практических задач.</li>
            <li>По итогу прохождения курса вы
                пополните свое портфолио тремя практическими проектами и получите сертификат о прохождении курса.</li>
            <li>Для того чтобы получить сертификат и доступ к курсу - необходимо подать заявку на программу
            "Практический Python" в <a href="https://xn--52-kmc.xn--80aafey1amqq.xn--d1acj3b/program/45942-prakticheskii-python" target="_blank">Навигаторе дополнительного образования</a></li>
        </ul>
    </div>

    <div class="main_moments">
        <div class="swiper mySwiper">
            <h3>Основное</h3>
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <figure>
                        <h2>Алексеев Иван Иванович - автор и преподаватель курса</h2>
                        <img src="{% static 'main/images/teacher/Ivan_Alekseev_1.png' %}" alt="Certificate">
                        <figcaption>
                            <a href="{% url 'main:teacher' %}" class="btn btn-lg btn-success" style="margin-top: 10px">Читать подробнее</a>
                        </figcaption>
                    </figure>
                </div>
                <div class="swiper-slide">
                    <figure>
                        <h2>Сертификат по итогу прохождения курса</h2>
                        <img src="{% static 'main/images/certificate/certificate.jpg' %}" width="200px" height="291px" alt="Certificate">
                    </figure>
                </div>
                <div class="swiper-slide">
                    <figure>
                        <h2>Наш курс на Youtube</h2>
                        <iframe width="450" height="291" src="https://www.youtube.com/embed/videoseries?si=D8jznaTDposEGtNU&amp;list=PLn6kz1xByugtaOa2CeA2IQldXmlpWOROj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                        <figcaption>
                            <a target="_blank" href="https://www.youtube.com/embed/videoseries?si=D8jznaTDposEGtNU&amp;list=PLn6kz1xByugtaOa2CeA2IQldXmlpWOROj" class="btn btn-lg btn-success" style="margin-top: 10px">Открыть</a>
                        </figcaption>
                    </figure>
                </div>
                <div class="swiper-slide">
                    <figure>
                        <h2>Что включает в себя курс?</h2>
                        <div style="text-align: left; padding-left: 10px">
                            <h4 style="padding-top: 15px; font-size: 14pt">4 практических модуля:</h4>
                            <ul style="padding: 0; font-size: 12pt">
                                <li style="padding-bottom: 7px;">Модуль 1. Основы Python:<br>
                                Изучение основ языка программирования Python</li>
                                <li style="padding-bottom: 7px;">Модуль 2. Основы Django:<br>
                                Разработка сайта с использованием фрэймворка Django</li>
                                <li style="padding-bottom: 7px;">Модуль 3. Разработка чат-ботов:<br>
                                Разработка Telegram чат-бота на PytelegramApi</li>
                                <li>Модуль 4. Разработка 2D-игры:<br>
                                Разработка 2D-игры на PyGame</li>
                            </ul>
                        </div>
                        <figcaption>
                            <a href="{% url 'main:modules' %}" class="btn btn-lg btn-success" style="margin-top: 10px">Читать подробнее</a>
                        </figcaption>
                    </figure>
                </div>
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </div>

    <div class="course_content">
        <h3>Структура курса</h3>
        <p>Наш курс имеет модульную структуру и разделен на 4 практических модуля, которые будут открываться по
        ходу прохождения курса.<br><br>В каждом модуле вы будете шаг за шагом проходить выстроенные в логической
        последовательности темы, взаимосвязанные между собой. По итогу прохождения каждой темы вам
        будет предложено выполнить домашнее задание, состоящее из ряда практических задач.<br><br>Каждому участнику
        на протяжении прохождения курса будет дана обратная связь по решению домашних задач и возникающим вопросам,
        которые можно задавать в группах в
        <a href="https://t.me/+HXHMJPBWdUcyZDFi" target="_blank">Telegram</a> или
        <a href="https://vk.me/join/71b1yYYGbyuuOQGdBw8ec6YXaqESLqyHevI=" target="_blank">VK</a>. Также в
        течение прохождения каждого модуля будут организованы несколько онлайн встреч на платформе
        <a href="https://discord.gg/EUTJSmF4" target="_blank">Discord</a>, даты которых вы сможете найти в разделе
        <a href="{% url 'main:schedule' %}">Расписание</a>.<br><br>Теорию и разбор задач по каждой теме вы сможете найти в
        текстовом виде на нашем сайте, а также в формате видео на
            <a href="https://youtube.com/playlist?list=PLn6kz1xByugtaOa2CeA2IQldXmlpWOROj&si=eRz9tUxn9I8GxF3I"
               target="_blank">Youtube</a></p>
    </div>

    <div class="teacher">
        <h3>Автор и преподаватель курса</h3>
        <img src="{% static 'main/images/teacher/Ivan_Alekseev_1.png' %}" alt="teacher">
        <div class="about_teacher">
            <h4 style="font-size: 16pt"><a href="{% url 'main:teacher' %}">Алексеев Иван Иванович</a></h4>
            <ul>
                <li>Студент Радиофизического факультета ННГУ им. Лобачевского, направления Информационная безопасность
                телекоммуникационных систем. Преподаватель программирования в <a href="https://greensailnn.ru" target="_blank">
                ДЮЭЦ "Зеленый парус".</a></li>
                <li>Занимается программированием с 10 класса.</li>
                <li>Проходил курсы на различных платформах,
                    факультатив по программированию на JavaScript в рамках обучения в университете.</li>
                <li>Занимается разработкой чат-ботов
                на различных платформах, разработкой сайтов и интерфейсов, анализом данных</li>
                <li>Имеет опыт программирования на языках C, C++, Java, JavaScript, Python. Основной язык
                    программирования  - Python</li>
                <li>Имеет опыт построения и администрирования баз данных MySQL, PostgreSQL, SQlite3</li>
                <li>Ссылка на GitHub: <a href="https://www.youtube.com/embed/videoseries?si=D8jznaTDposEGtNU&amp;list=PLn6kz1xByugtaOa2CeA2IQldXmlpWOROj" target="_blank">IvanA-19</a></li>
            </ul>
        </div>
    </div>

    <div class="for_users">
        <h3>Кому подойдет данный курс?</h3>
        <p>Данный курс рассчитан на потенциальных обучающихся в возрасте от 14 до 18 лет. Курс подойдет, как для новичков,
        так и для тех, у кого уже имеется опыт в программировании и они желают повысить свой уровень, поучаствовать в
        разработке серьезных практических проектов. В рамках курса, благодаря общению между собой, обучающиеся также смогут
        повысить уровень "мягких навыков" - soft skills, получить опыт работы в команде, приобрести ценные знания.</p>
    </div>

    <div class="contacts">
        <h3>Контактная информация</h3>
        <ul>
            <li>Социальные сети и мессенджеры:</li>
            <li>VK: <a href="https://vk.com/alekseev_i260303" target="_blank">Иван Алексеев</a></li>
            <li>Telegram: <a href="https://t.me/Vanyok77797" target="_blank">@Vanyok77797</a></li>
            <li>Discord: <a href="https://vk.com/away.php?utf=1&to=https%3A%2F%2Fdiscord.gg%2FuF8JVREF">v_a_n_y_o_k77797</a></li>
            <li>Электронная почта: alekseev.i260303@gmail.com</li>
        </ul>
        <p>Обращаться по вопросам, связанным с сайтом, личным кабинетом</p>
    </div>

    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'slider/css/swiper-bundle.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'slider/css/slider.css' %}">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="{% static 'slider/js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'slider/js/slider.js' %}"></script>


{% endblock %}

main/templates/main/module.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}{{module}}{% endblock %}

{% block page_header %}
    <h1>{{module}}</h1>
{% endblock %}


{% block content %}
    <ul class="topics">
        {% for topic in topics %}
            <li>
                <div class="topic">
                    <h4>{{topic}}</h4>
                    {% if topic.description|length > 250 %}
                        <p id="topic_{{topic.id}}_text">{{topic.description|slice:250}}...</p>
                    <button class="btn" style="background-color: #8A2BE2; color: white;"
                                    onmouseover="this.style.backgroundColor='#9400D3'"
                                    onmouseout="this.style.backgroundColor='#8A2BE2'"
                                    onclick="full_text(`{{topic.description}}`, `{{topic.id}}`)"
                        id="show_button_{{topic.id}}">Читать полностью</button>
                        <div id="hide_{{topic.id}}" style="margin-bottom: 10px;"></div>
                        <a href="{% url 'main:topic' topic.topic_slug %}" class="btn btn-success">Перейти к теме</a>
                    {% else %}
                        <p>{{topic.description|linebreaks}}</p>
                        <a href="{% url 'main:topic' topic.topic_slug %}" class="btn btn-success">Перейти к теме</a>
                    {% endif %}
                </div>
            </li>
            {% empty %}
                <li>
                    <div class="topic">
                        <h4>Первый урок появится 07.03.2024.</h4>
                    </div>
                </li>
        {% endfor %}
    </ul>

    <link rel="stylesheet" href="{% static 'main/css/module.css' %}">
    <script src="{% static 'main/js/topic.js' %}"></script>

{% endblock %}

main/templates/main/modules.html
{% extends 'main/base.html' %}
{% load static %}


{% block title %}Модули{% endblock %}

{% block page_header %}
    <h1>Модули</h1>
{% endblock %}


{% block content %}
    <ul class="modules">
        {% for module in modules %}
            {% if module.enabled %}
                <li>
                    <div class="module">
                        <img src="{% static 'main/images/modules/module_1_preview.jpg' %}" alt="preview">
                        <h3><a href="{% url 'main:module' module.module_slug %}">{{module}}</a></h3>
                        {% if module.description|length > 500 %}
                            <p id="module_{{module.id}}_text">{{module.description|slice:500}}...</p>
                            <button class="btn btn-lg" style="background-color: #8A2BE2; color: white;"
                                        onmouseover="this.style.backgroundColor='#9400D3'"
                                        onmouseout="this.style.backgroundColor='#8A2BE2'"
                                        onclick="full_text(`{{module.description}}`, `{{module.id}}`)"
                            id="show_button_{{module.id}}">Читать полностью</button>
                            <div id="hide_{{module.id}}" style="margin-bottom: 10px;"></div>
                        {% else %}
                            <p>{{module.description|linebreaks}}</p>
                        {% endif %}
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>

    <link rel="stylesheet" href="{% static 'main/css/module.css' %}">
    <script src="{% static 'main/js/module.js' %}"></script>
{% endblock %}

main/templates/main/topic.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}{{topic}}{% endblock %}

{% block page_header %}
    <h1>
        <a href="{% url 'main:module' topic.module.module_slug %}"
        style="font-size: 22pt; color: #156632">{{topic.module}}</a>
    </h1>
{% endblock %}

{% block content %}
    <div class="lesson">
        <h2>{{topic}}</h2>
        <ul class="subtopics">
            {% for subtopic in subtopics %}
                <li>
                    <div class="subtopic">
                        <h4>{{subtopic}}</h4>
                        <p>{{subtopic.content}}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <h3>
            {% if topic.video %}
                Ссылка на видео-разбор занятия: <a href="{{topic.video}}" target="_blank">{{topic.video}}</a><br>
            {% endif %}
            {% if topic.link %}
                Ссылку на решение домашних задач указать в google-форме: <a href="{{topic.link}}">{{topic.link}}</a>
            {% endif %}
        </h3>
    </div>

    <link rel="stylesheet" href="{% static 'main/css/topic.css' %}">

{% endblock %}